plugins {
    alias(libs.plugins.android.application)
}

android {

    signingConfigs {
        release {
            storeFile file('../keystore/rdpkeybridge.jks')
            storePassword 'rdpkeybridge'
            keyAlias 'rdpkeybridge'
            keyPassword 'rdpkeybridge'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    namespace 'io.github.pingdongyi.rdpkeybridge'
    compileSdk 35

    defaultConfig {
        applicationId "io.github.pingdongyi.rdpkeybridge"
        minSdk 28
        targetSdk 35
        versionCode 17
        versionName "1.16"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
    implementation libs.dexkit
    // DexKit 的 Kotlin API 需要 kotlin-stdlib 参与编译（其 POM 中为 runtime scope）
    implementation libs.kotlin.stdlib
}
